# Module: kibana
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.7/metricbeat-module-kibana.html

- module: kibana
  #metricsets:
  #  - status
  period: 10s
  hosts: ["${ES_HOST}:5601"]
  #basepath: ""
  #username: "user"
  #password: "secret"
